version: '3.4'

services:
  shippingdb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  shippingWdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  mongo-express:
    image: mongo-express
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@shippingdb:27017

  rabbitmq:
   image: rabbitmq:3-management-alpine

  shipping:
    image: ${DOCKER_REGISTRY-}shippingapi
    build:
      context: .
      dockerfile: Shipping/Shipping/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  elasticsearch-data: