version: '3.4'

services:
  shippingdb:
   image: mongo

  rabbitmq:
   image: rabbitmq:3-management-alpine

  shipping:
    image: ${DOCKER_REGISTRY-}shippingapi
    build:
      context: .
      dockerfile: Shipping/Shipping/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  mongo_data:
  elasticsearch-data: